### ISSUE TITLE
使用1.2.0版本后添加中间按钮后运行后会报错（闪退）

### ISSUE THREAD

**Issue by bby0856** [peng8350/JPTabBar#10]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.haorui.myjptable/com.haorui.myjptable.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class com.jpeng.jptabbar.JPTabBar

  Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.jpeng.jptabbar.JPTabBar

您给看看啊

> 

> <RelativeLayout

> 

> 

> 

 xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:jp="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.haorui.myjptable.MainActivity">

    <com.jpeng.jptabbar.JPTabBar
        android:id="@+id/tabbar"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:background="#fff"
        jp:TabTextSize="12sp"
        jp:TabMiddleIcon="@mipmap/ic_launcher"
        />
</RelativeLayout>

public class MainActivity extends AppCompatActivity {
    @Titles
    private static final String[] mTitles = {"页面一","页面二","页面三","页面四"};

    @SeleIcons
    private static final int[] mSeleIcons = {R.mipmap.ic_launcher,R.mipmap.ic_launcher,R.mipmap.ic_launcher,R.mipmap.ic_launcher};

    @NorIcons
    private static final int[] mNormalIcons = {R.mipmap.ic_launcher, R.mipmap.ic_launcher, R.mipmap.ic_launcher, R.mipmap.ic_launcher};
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}

repositories {
    jcenter()
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.jpeng:JPTabBar:1.2.0'
}

**Comment by peng8350** [comment]
这个问题，昨天已经有人提到了，也发现了问题所在，参考#8，#9。使用代码初始化不用注解就不会蹦。
