### ISSUE TITLE
小红点拖拽动画开始位置不对，应该在上端吧？为什么每次都是从底部

### ISSUE THREAD

**Issue by JinJieGu** [peng8350/JPTabBar#12]

**Comment by peng8350** [comment]
不太明白,拖拽动画一般是跟随着手指触摸的位置,是否可给几个截图加上调试设备?

**Comment by JinJieGu** [comment]
Bug效果如下：

![snip20170503_2](https://cloud.githubusercontent.com/assets/11242805/25652479/fd856458-301a-11e7-8421-aeb110e11b63.png)

我简单地研究了下作者的源码和demo，发现产生这种情况的原因是因为我的showBadge方法是放在了onCreate中调用的，作者的源码中有两段代码是对画布去除状态栏的偏移处理，例如DragBadgeView 中#199 的代码：
`canvas.translate(0, -BadgeViewUtil.getStatusBarHeight(mBadgeViewHelper.getRootView()));
`
而作者BadgeViewUtil.getStatusBarHeight的方法是通过应用区域的top属性推算的出状态栏的高度
（`view.getRootView().getWindowVisibleDisplayFrame(rectangle);`）
而这种方式的弊端也很明显，就是必须依赖窗口回调机制，也就是需要等onWindowFocusChanged执行后才能调用，所以我放到onCreate中调用showBadge时拿到的StatusBarHeight是0，就出现了标题中我所描述的bug。

等会我会PR一个解决方案，作者可以参考一下。
