### ISSUE TITLE
请问下从tab3页面跳转到某个Activity页 然后finish掉  回到主页怎么选中tab1页面？

### ISSUE THREAD

**Issue by ywanhzy** [peng8350/JPTabBar#14]
请问下从tab3页面跳转到某个Activity页 然后finish掉  回到主页怎么选中tab1页面？

**Comment by peng8350** [comment]
利用onActivityresult回调，调用控件的setSelectTab(0)就是切换第一个页面了

**Comment by ywanhzy** [comment]
@peng8350  调用了这个方法mTabBar.setSelectTab(0); 底部tab栏是切换过去了  但view_pager 内容还是显示的tab3 而不是tab1

**Comment by JoviLam** [comment]
”调用了这个方法mTabBar.setSelectTab(0); 底部tab栏是切换过去了 但view_pager 内容还是显示的tab3 而不是tab1“      请问这个问题解决了吗

**Comment by peng8350** [comment]
你们没有调setContainer这个方法吧？

**Comment by ywanhzy** [comment]
在Tab3Pager页面怎么调用mTabBar.setContainer(ViewPager);  ViewPager值怎么取？

**Comment by JoviLam** [comment]
我是调完setSelectTab(0)之后再调用viewpager的setCurrentItem(0)解决的

**Comment by ywanhzy** [comment]
@JoviLam 谢谢  可以了
