### ISSUE TITLE
设置默认选中第2个itme，怎么让ViewPager 显示对应的Fragment

### ISSUE THREAD

**Issue by AllLuckly** [peng8350/JPTabBar#21]
mTabbar.setSelectTab(1);这样设置的

**Comment by peng8350** [comment]
在你调用了setContainer绑定的情况下,直接mTabbar.setSelectTab(1)就可以,选择不绑定ViewPager,调用完这个方法后还要调用viewpager的setCurrentItem(1)方法来改变页面
