### ISSUE TITLE
我想点击某个tab判断用户是否登录，没登录直接去登录页面。没有这个回调。

### ISSUE THREAD

**Issue by Carlxx** [peng8350/JPTabBar#24]
我想点击某个tab判断用户是否登录，没登录直接去登录页面。没有这个回调。是否可以更新下

**Comment by peng8350** [comment]
setTabListener可以设置监听

**Comment by Carlxx** [comment]
因添加的依赖不想添加lib包，所以希望只更新库添加监听。不然，只能我这里修改代码了。
在没有切换fragment 之前拦截，获取监听，setTabListener
 @Override
    public void onTabSelect(int index) {

        switch (index) {
            case 2:
                startActivity(new Intent(this, LoginActivity.class));
                break;
            default:

        }

    }
这时已经加载显示了，如用的不对，望 楼给出代码。

**Comment by peng8350** [comment]
你是想假设没有登录的话,直接跳转登录页面,而不改变tab和页面,需求是这样的,没错吧?

**Comment by Carlxx** [comment]
没错。没登录直接去登录。tab还是之前显示的不变。市面有挺多这种需求的，因为楼主的库方便，所以希望楼主，添加这样的回调 。同时我们少去了自己添加lib，修改源码的麻烦了，谢谢了=_=

**Comment by peng8350** [comment]
嗯...不过,我这里要兼容页面滑动动画会有点麻烦

**Comment by Carlxx** [comment]
^_^那等待版本更新了~
