### ISSUE TITLE
中间按钮没突出啊

### ISSUE THREAD

**Issue by weijuner** [peng8350/JPTabBar#6]
中间按钮没突出啊

**Comment by peng8350** [comment]
估计是你的图片有边距吧，你试下使用自带的iclauther就知道我什么意思了。

**Comment by weijuner** [comment]
用的是自带的，确实没突出

**Comment by peng8350** [comment]
截个图,复制个tabbar控件代码我看看

**Comment by weijuner** [comment]
有突出，不过太不明显了，如果能自定义突出高度就好了

**Comment by peng8350** [comment]
待解决!之前我是想提供的,但是一直解决不了一个问题就是:超出的范围无法响应点击事件!
