### ISSUE TITLE
能否增加设置属性的方法

### ISSUE THREAD

**Issue by xuhuan** [peng8350/JPTabBar#7]
比如 TabIconSize 这个目前只能在xml设置,没办法代码设置,目前需求需要根据条件动态初始化图标大小.
其他属性目前没用到,不过如果可以的话能否尽量其他的xml设置的属性也增加对应的方法.
@peng8350

**Comment by peng8350** [comment]
内部已经提供了getMiddleIcon方法，可以获得中间图标的对象

**Comment by xuhuan** [comment]
不是中间图标,是底部所有的图标,也就是iconSize这个值.之前你没回应我就自己fork了一份增加了这个属性,如果不清楚的话可以看下我fork改过的地方应该能明白. @peng8350
