### ISSUE TITLE
NullPointerException when declare/initialize JPTabbar in Lollipop 5.1.0

### ISSUE THREAD

**Issue by arrivaldwis** [peng8350/JPTabBar#8]
Thanks for your awesome library, it's works in almost all device. but i have a problem when it run on Asus Fonepad 8 (Lollipop 5.1.0) it's crash and said NullPointerException at all of tabbar initialize

**Comment by peng8350** [comment]
Can you show me some logs about the crash?

**Comment by arrivaldwis** [comment]
I set onTabListener after declared the jptabbar as mTabbar.

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jpeng.jptabbar.JPTabBar.setTabListener(com.jpeng.jptabbar.OnTabSelectListener)' on a null object reference
>                                                                                                 at com.dios.idolinkz.MainPageActivity.onCreate(MainPageActivity.java:135)
>                                                                                                 at android.app.Activity.performCreate(Activity.java:5990)
>                                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>                                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>                                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
>                                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>                                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
>                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                                 at android.os.Looper.loop(Looper.java:135) 
>                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
>                                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
>                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

and it's also happen to others (not only onTabListener) to other method that i called for mTabbar

**Comment by peng8350** [comment]
It seems that the mTabBar you declare is null.The problem about some devices crashed by NullPointer I haven't met before.and I don't have the device that you said now.But if you find the same problem in genymotion,you can tell the genymotion id and I will test it!!

**Comment by arrivaldwis** [comment]
Yes It's also happen in genymotion, I use emulator "Custom Tablet - 5.1.0 API 22"

**Comment by peng8350** [comment]
Oh!I find the bug,The problem is not the device,I forgot to check annotation initialize methods with middle button, Another init method is not problem,I will fix it .Thanks!

**Comment by arrivaldwis** [comment]
Thanks for your update, but I still get this crash
