### ISSUE TITLE
添加了中间按钮  就闪退

### ISSUE THREAD

**Issue by yuyuesheng** [peng8350/JPTabBar#9]
logcat

Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.jpeng.jptabbar.JPTabBar

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.jpeng.jptabbar.JPTabBar
        android:id="@+id/jptabbar"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:background="@color/white"
        app:TabMiddleBottomDis="14dp"
        app:TabMiddleHMargin="36dp"
        app:TabMiddleIcon="@mipmap/release2"
        app:TabTextSize="12sp" />

    <FrameLayout
        android:id="@+id/fl_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
`

**Comment by peng8350** [comment]
把app:TabMiddleIcon结点去掉后,就不闪退? 试下换张图片,顺便把XML全部代码粘贴我看下

**Comment by yuyuesheng** [comment]
<?xml version="1.0" encoding="utf-8"?>
布局

1. <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
2.     xmlns:app="http://schemas.android.com/apk/res-auto"
3.     xmlns:tools="http://schemas.android.com/tools"
4.     android:layout_width="match_parent"
5.     android:layout_height="match_parent">
6. 
7.     <FrameLayout
8.         android:id="@+id/fl_main"
9.         android:layout_width="match_parent"
10.         android:layout_height="match_parent" />
11. 
12.     <com.jpeng.jptabbar.JPTabBar
13.         android:id="@+id/jptabbar"
14.         android:layout_width="match_parent"
15.         android:layout_height="56dp"
16.         android:background="@color/white"
17.         app:TabMiddleBottomDis="0dp"
18.         app:TabMiddleIcon="@mipmap/release2" />
19. 
20. </RelativeLayout>
